mvp
deeppavlov/dream-builder pull request #7
Opened 2022-11-02 09:54 UTC by klmntv

2022-11-02 11:22 UTC, mtalimanchuk requested changes

2022-11-02 11:22 UTC, mtalimanchuk commented on services/frontend/.gitignore
> +# Logs
объедини с .gitignore в корне, а этот удали

2022-11-03 11:47 UTC, TimofeySyrov approved these changes

2022-11-03 12:59 UTC, klmntv commented on services/frontend/.gitignore
> +# Logs
готово

2022-11-09 12:47 UTC, mtalimanchuk approved these changes

2022-11-09 12:47 UTC, merged